### ISSUE TITLE
Transfer deployment manifests from https://github.com/AICoE/aicoe-cd

### ISSUE THREAD

**Issue by durandom** [operate-first/continuous-deployment#1]
Copy all content from https://github.com/AICoE/aicoe-cd to this repo, with any implementation details stripped, e.g. clusternames, dev, prod etc

The idea is to use this repo as an upstream repo, which is agnostic of the target environment. 

The only app to be included should be the argocd guestbook example

**Comment by HumairAK** [comment]
Updated scope of this ticket to only include deployment manifests that are generalized from `aicoe-cd` the rest will be handled by other issues.
