### ISSUE TITLE
Move argocd manifests to apps repo?

### ISSUE THREAD

**Issue by HumairAK** [operate-first/continuous-deployment#113]
I think this repo has become a bit of a snowflake because we store all our cluster resources in the apps repo but make an exception for the cluster rbac/crds for argocd because they go in this repo. I'm thinking we should just move all of the argocd stuff into an argocd app in the apps repo, we just keep this repo alive for the docker file + tag releases. We also move the docs too, so that we have one less repo to worry about when debating where a certain piece of documentation lives. WDYT?

Edit: Laying down plan for migration here: 

- [x] first move argocd manifests folder, and store cluster resources in cluster-scope app 
- [ ] ~move scripts to the apps repo scripts folder~ We'll just remove these and delegate fresh install steps to markdown
- [x] move docs to the apps docs folder 
- [x] update downstream `aicoe-cd` repo manifests to point to the apps/argocd/base path
- [x] remove manifests/scripts/docs from this repo
- [ ] rename this repo to a more appropriate name that houses argocd image

**Comment by 4n4nd** [comment]
Yeah moving this to the apps repo does make sense, I don't think that would affect the image building. Maybe we will need to make minor changes to the Dockerfile for it, but other than that it should be good :+1:

**Comment by tumido** [comment]
I think consolidation is a good thing to do. However this is not an urgent pressing issue right now. :slightly_smiling_face: 

I vote yes. I'm adding this into our backlog.

**Comment by HumairAK** [comment]
Manifests were moved, all pr's making changes to manifests should be directed to the `apps` repo henceforth.

**Comment by HumairAK** [comment]
Okay one thing that slipped my mind is how we tag released argocd manifests/configs in this repo for downstream to consume: https://github.com/AICoE/aicoe-cd/blob/main/manifests/base/kustomization.yaml#L4 

With argocd now in apps repo, we need to come up with a nice clean way for downstream to reference our manifests. The proposed method will also be extended to other apps.

**Comment by HumairAK** [comment]
My initial thought was to create separate tags in the `apps` repo for the apps we want to snapshot, but that _may_ be messy for us, we could have downstream reference a commit, but that would be messy for them.

**Comment by anishasthana** [comment]
I think tags in the apps repo makes the most sense. Referencing commits doesn't say all that much.

**Comment by tumido** [comment]
I don't like tagging apps if the tag is connected just to a single application in the whole repo. I don't want to make this community's main repo look messy and confusing for the AiCoE ArgoCD's sake. I actually think tagging commits is fine for now. At some point this will diverge eventually, since Operate First should convert to Gitops Operator at some point. I don't think we have that plan for AiCoE anyways, in any case the overlap between these repos becomes minimal.

**Comment by HumairAK** [comment]
Yep that's fine with me.

**Comment by HumairAK** [comment]
I think we can call this done.
