### ISSUE TITLE
Enable anonymous read access

### ISSUE THREAD

**Issue by tumido** [operate-first/continuous-deployment#116]
Currently an unauthenticated user sees:
![image](https://user-images.githubusercontent.com/7453394/109153556-5cfa9a00-776d-11eb-82b8-47ad8385ddcc.png)

We need to fix this, since we are multi cluster now and we might not want to have user parity between clusters - like for the workshops for example.

**Comment by HumairAK** [comment]
~What kind of apps/resources would you like to see be readable by anonymous?~
Just noticed the pr

**Comment by tumido** [comment]
Resolved by a custom default role allowing users to view applications in the `workshops` project only.
