### ISSUE TITLE
add argocd application of deploying the ODH operator to quicklab fork

### ISSUE THREAD

**Issue by durandom** [operate-first/continuous-deployment#14]
* deploy via OLM upstream
* are we able to lock the ODH operator version?

**Comment by martinpovolny** [comment]
Going to take this one.

**Comment by martinpovolny** [comment]
The steps for CRC: https://github.com/operate-first/continuous-deployment/blob/master/docs/downstream/odh-install-crc.md CRC worked for me w/o change also for Quicklab.

The only change I did was editing the "cluster" in the https://github.com/operate-first/continuous-deployment/blob/master/examples/odh-deployment-app.yaml and https://github.com/operate-first/continuous-deployment/blob/master/examples/odh-operator-app.yaml
This should be somehow parametrized.
