### ISSUE TITLE
[discussion] Rename repo to something more specific

### ISSUE THREAD

**Issue by HumairAK** [operate-first/continuous-deployment#15]
cd -- is a bit vague

Suggestions?

**Comment by anishasthana** [comment]
Expand it to continuous-deployment?

**Comment by durandom** [comment]
continuous-delivery has the longer wikipedia entry:

https://en.wikipedia.org/wiki/Continuous_delivery
https://en.wikipedia.org/wiki/Continuous_deployment

**Comment by HumairAK** [comment]
operate-first-cd ? 
ofcd ?

**Comment by durandom** [comment]
I'm a fan of self explaining names, and we don't need the `operate-first` prefix, since it's already in the org.
So, I would go with either `continuous-deployment` or `continuous-delivery`

**Comment by HumairAK** [comment]
I think I agree with that too. 

From the wiki entry above
```
CD (continuous delivery) contrasts with continuous deployment, a similar approach in which software is also produced in short cycles but through automated deployments rather than manual ones.
```
I vote for `continuous-deployment` then.

**Comment by hemajv** [comment]
:+1:  for `continuous-deployment`

**Comment by durandom** [comment]
@HumairAK do you want to rename to `continuous-deployment` then?

**Comment by HumairAK** [comment]
@durandom yes can you rename it to `continuous-deployment` ? I don't have the permissions to do this :)

**Comment by durandom** [comment]
done
