### ISSUE TITLE
get access to MOC CNV cluster

### ISSUE THREAD

**Issue by durandom** [operate-first/continuous-deployment#16]
to deploy ODH

**Comment by durandom** [comment]
@HumairAK @anishasthana what do we need to get ODH installed to a OCP4.5 cluster? `cluster-admin` for your personal user account?

**Comment by durandom** [comment]
Opened an issue at https://gitlab.com/open-infrastructure-labs/moc-cnv-sandbox/-/issues/26

**Comment by anishasthana** [comment]
Cluster admin for the two of us is sufficient for now

**Comment by HumairAK** [comment]
It would be nice if we have cluster admin, but we continue to maintain namespace installations, this would make it easier to install crd's and such without having to communicate across teams etc.

**Comment by HumairAK** [comment]
CNV Cluster was provisioned and access was granted, other communications I think can be delegated to [here](https://gitlab.com/open-infrastructure-labs/moc-cnv-sandbox)
