### ISSUE TITLE
container image with all cli dependencies

### ISSUE THREAD

**Issue by durandom** [operate-first/continuous-deployment#18]
To remove the dependency to install kustomize or sops, as mentioned in https://aicoe.github.io/aicoe-cd/setup_argocd_dev_enviornment/ - can we have those in containers and add shell aliases?

Let's have a toolbox container for this based on Fedora... see https://github.com/thoth-station/thoth-toolbox

**Comment by HumairAK** [comment]
Where do we want the toolbox image to live? `quay.io/aicoe/of-toolbox` ?

**Comment by HumairAK** [comment]
PR: https://github.com/operate-first/toolbox/pull/1

**Comment by HumairAK** [comment]
Toolbox with cli dependencies found here: https://github.com/operate-first/toolbox
