### ISSUE TITLE
add ArgoCD application of deploying the ODH operator to crc fork

### ISSUE THREAD

**Issue by durandom** [operate-first/continuous-deployment#27]
based on the quicklab steps

**Comment by martinpovolny** [comment]
This should be basically done as presented in "ODH Continuous Deployment Demo" by @anishasthana 
So I will try to reproduce the steps and make sure it runs with CRC.

**Comment by martinpovolny** [comment]
I have encountered a couple of issues while getting the ArgoCD deployment of ODH running on CRC.

One problem was with ArgoCD UI: upon editing a "Cluster" in the UI the secrets (SA token) from the cluster definition was removed and needed to be re-added using steps from https://github.com/martinpovolny/continuous-deployment-crc/blob/master/examples/configure_development.sh#L24
I have created an issue in ArgoCD: https://github.com/argoproj/argo-cd/issues/4405

Then there was an issue with the Operator Catalog in the CRC. I have created an issue here: https://github.com/operator-framework/operator-marketplace/issues/344

Howto PR: https://github.com/operate-first/continuous-deployment/pull/34
