### ISSUE TITLE
Quicklab and persistent storage

### ISSUE THREAD

**Issue by tumido** [operate-first/continuous-deployment#37]
Currently Openshift4 in Quicklab is lacking persistent storage - no PVs available on the cluster. Let's hope Quicklab team can help us out with that:

https://redhat.service-now.com/surl.do?n=INC1446454

**Comment by durandom** [comment]
@harshad16 @goern does your tekton setup work without PVs?

**Comment by harshad16** [comment]
> @harshad16 @goern does your tekton setup work without PVs?

yes, we had developed it in a way that it does require pv's.
As we were deploying on quicklab and it doesn't have pv support (as you already know)

**Comment by durandom** [comment]
Can we fake something with ceph mini? If that's still part of ODH

**Comment by harshad16** [comment]
> Can we fake something with ceph mini? If that's still part of ODH

is this question for me? i m not aware of ceph mini .

**Comment by durandom** [comment]
Sorry, it's called ceph-nano and we continued the discussion here: https://github.com/operate-first/continuous-deployment/issues/28#issuecomment-698850973

Maybe we can workaround a cluster setup without persistent storage, if we can use object storage.

**Comment by tumido** [comment]
FTR: Quicklab team replied to our ticket

> Unfortunately that Jira was pushed to the backlog. We would like to see it solved too but have many issues we are working on. If you need to discuss further, please reach out to the QL product owner Theo Apazoglou.

It seems I'll be reaching out to their PM directly then...
