### ISSUE TITLE
Deploy all ODH components (or as many as feasible)  on Quicklab and document process in cd repo

### ISSUE THREAD

**Issue by HumairAK** [operate-first/continuous-deployment#41]

**Comment by hemajv** [comment]
Supporting Documentation:
- https://github.com/operate-first/continuous-deployment/blob/master/docs/downstream/quicklab.md
- https://github.com/operate-first/continuous-deployment/blob/master/docs/downstream/on-cluster-persistent-storage/README.md
- https://github.com/operate-first/continuous-deployment/blob/master/docs/downstream/odh-install-quicklab.md

**Comment by martinpovolny** [comment]
here's a PR that documents adding an example component - prometheus

https://github.com/operate-first/continuous-deployment/pull/52

**Comment by martinpovolny** [comment]
@hemajv : and here are the steps linked in the correct order (as you wrote above): https://github.com/operate-first/continuous-deployment/blob/master/docs/index.md

Maybe add some text around to make it clear?

**Comment by hemajv** [comment]
> @hemajv : and here are the steps linked in the correct order (as you wrote above): https://github.com/operate-first/continuous-deployment/blob/master/docs/index.md
> 
> Maybe add some text around to make it clear?

@martinpovolny updated the index.md in https://github.com/operate-first/continuous-deployment/pull/62
