### ISSUE TITLE
Identify lag/manual points to Continuous Deployment Process and identify areas of improvement

### ISSUE THREAD

**Issue by HumairAK** [operate-first/continuous-deployment#42]
We should identify how long it takes to deploy argocd + odh + components on a _dev ocp cluster_ (crc or quicklab) and whether this is an acceptable time frame. 

If it is not - this should result in a concrete solution (e.g. a script) in the form of another issue.

**Comment by martinpovolny** [comment]
I am working on a script here: https://github.com/operate-first/continuous-deployment/pull/47

**Comment by HumairAK** [comment]
I think this issue has gone stale, overall I think we've made the process a lot more automated, we can continue to iterate.
