### ISSUE TITLE
kustomize stdout mess running under toolbox

### ISSUE THREAD

**Issue by martinpovolny** [operate-first/continuous-deployment#48]
when running kustomize from the toolbox using the 'run" command I get an information message in the stdout. Which is a problem if I want to pipe to `oc` or `kubectl` or anywhere

Compare:

```bash
$ kustomize build manifests/overlays/dev --enable_alpha_plugins 2>/dev/null  | head
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: application-controller
    app.kubernetes.io/name: argocd-application-controller
    app.kubernetes.io/part-of: argocd
  name: argocd-application-controller
  namespace: aicoe-argocd-dev
---
```

vs:
```bash
$ toolbox run --container of-toolbox-v0.1.0 kustomize build manifests/overlays/dev --enable_alpha_plugins 2>/dev/null | head
2020/10/05 09:46:56 Attempting plugin load from '/usr/share/.config/kustomize/plugin/viaduct.ai/v1/ksops/ksops.so'
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: application-controller
    app.kubernetes.io/name: argocd-application-controller
    app.kubernetes.io/part-of: argocd
  name: argocd-application-controller
  namespace: aicoe-argocd-dev
```

Using `toolbox enter` is ok too:
```bash
$ toolbox enter --container of-toolbox-v0.1.0
...
...
$ kustomize build manifests/overlays/dev --enable_alpha_plugins 2>/dev/null | head
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: application-controller
    app.kubernetes.io/name: argocd-application-controller
    app.kubernetes.io/part-of: argocd
  name: argocd-application-controller
  namespace: aicoe-argocd-dev
---
```

So this is probably something that needs to be reported back to toolbox. Or is it an expected behavior?

**Comment by HumairAK** [comment]
So I'm guessing you are referring to this text: 
`2020/10/05 09:46:56 Attempting plugin load from '/usr/share/.config/kustomize/plugin/viaduct.ai/v1/ksops/ksops.so'` 

This is coming from the kustomize build operation, but it's coming from stderr and not stdout. When you run the folowing commands it's captured by `2>/dev/null`: 
```
$ kustomize build manifests/overlays/dev --enable_alpha_plugins 2>/dev/null  | head
```
or 
```
$ toolbox enter --container of-toolbox-v0.1.0
$ kustomize build manifests/overlays/dev --enable_alpha_plugins 2>/dev/null | head
```
But when you run: 
```
$ toolbox run --container of-toolbox-v0.1.0 kustomize build manifests/overlays/dev --enable_alpha_plugins 2>/dev/null | head
```
I _think_ what's happening here is that, the command you are passing to toolbox is: 
```
 kustomize build manifests/overlays/dev --enable_alpha_plugins
``` 
then the result of this `toolbox run` (which includes stderr output) is sent to stdout. The command `2>/dev/null` is redirecting basically nothing to /dev/null.

**Comment by HumairAK** [comment]
As said in the previous comment, this looks like it's expected, if you can capture the `2>/dev/null` as part of the command sent to toolbox run then that should solve your problem, closing issue -- please re-open if this continues to pose a problem.
