### ISSUE TITLE
Add monitoring and Long Term Storage for Metrics

### ISSUE THREAD

**Issue by 4n4nd** [operate-first/continuous-deployment#57]
We can set up individual application monitoring using the ODH monitoring (Prometheus and Grafana Operators) and for long term storage of metrics we can use the Observatorium stack to set up the Thanos Infrastructure. (https://github.com/observatorium)

Proposed Solution:
1. Deploy ODH Prometheus and ODH Grafana + applications to monitor
2. Determine if we need one prometheus instance to monitor all namespaces or individual namespace prometheus instances
3. Deploy Observatorium (disable the Loki setup)
4. Update ODH Prometheus Manifest to remote write to Observatorium

@HumairAK @anishasthana @durandom

**Comment by HumairAK** [comment]
With regards to using one prometheus instance (no. 2 above) 

So the way I understanding, if we were using one kfdef, and everything was being deployed to the same namespace then, simply by installing prom via odh would set up monitoring for multiple components. 

But as per the docs [here](https://github.com/operate-first/odh/pull/3) we are going with multiple namespaces, i.e. a kfdef per component in odh, so we need to explore whether odh monitoring set up will still work, if not then what additional stuff we need to add (then relay back to odh team) to _make it work_. 

If we go with multiple prometheus per namespace, then every kfdef should include the prometheus component. We would then need a single prometheus to aggregate important metrics from the various individual prometheus via federation.

**Comment by anishasthana** [comment]
Sounds about right. The federation should be very straightforward though. I still think we're going to have lots of feedback for upstream ODH about this monitoring bit. (ODH should not manage a subscription to prometheus/grafana imo as this is something multiple different teams in a shared cluster would need to use, and having one operator gate versions of another shared operator seems like an anti-pattern)

**Comment by durandom** [comment]
@4n4nd can we start with installing the ODH stock monitoring stack as it is now? I guess that would involve a PR to https://github.com/operate-first/odh with the installed components to be installed

**Comment by 4n4nd** [comment]
I think that would be a good starting point. Once we do that, we can try to sort the connection between the odh monitoring stack and Observatorium.

**Comment by HumairAK** [comment]
Issue here to deploy on moc using prom/graf via odh [here](https://github.com/operate-first/SRE/issues/11)

**Comment by anishasthana** [comment]
@HumairAK that's the wrong issue isn't it?

**Comment by HumairAK** [comment]
derp yes, fixed

**Comment by 4n4nd** [comment]
Because of Openshift using Prometheus-operator for cluster monitoring, we cannot install our own instance of the Prometheus Operator cluster-wide. We could somehow install it for multiple namespaces but multi-namespace installations will be deprecated in the future. 
The CoreOS-monitoring team suggested using the openshift user workload monitoring but it is still in Tech Preview rn (openshift 4.5) and should be GA in openshift 4.6. I am testing the user workload monitoring, but the documentation is sparse. 

We could start with deploying the Prometheus operator in multinamespace mode and since the openshift user workload monitoring uses Prometheus Operator under the hood, we should be able to use the same CRs to then later move to openshift user workload monitoring when it is GA.

**Comment by HumairAK** [comment]
Issue is stale, and:

The strategy has evolved a bit, see [here](https://github.com/operate-first/apps/pull/123/files) and [the adr here](https://github.com/operate-first/blueprint/blob/main/docs/adr/0006-monitoring-structure.md) for more info.

We also already have an issue for [adding thanos](https://github.com/operate-first/apps/issues/74) which would cover long term storage.
