### ISSUE TITLE
Deploy all odh components on quicklab using operate-first/odh repo

### ISSUE THREAD

**Issue by HumairAK** [operate-first/continuous-deployment#60]
We want to replicate quicklab/crc deployments as closely to how we want to deploy on moc. This means using the odh repo to deploy the manifests using argocd. There maybe some issues with resource usage, part of this issue should be investigating how to reconcile such problems. 

This issue should build on the issue [here](https://github.com/operate-first/continuous-deployment/issues/41) and follow on https://github.com/operate-first/odh/issues/9

**Comment by hemajv** [comment]
This follows on #66

**Comment by HumairAK** [comment]
I think we can abandon this issue for the one linked above.
