### ISSUE TITLE
[discussion] Kustomize Plugin Directory

### ISSUE THREAD

**Issue by HumairAK** [operate-first/continuous-deployment#8]
I would like to start a discussion about using kustomize plugins to extend the functionality of kustomize to meet our needs. Some existing problems right now: 

- Kafkatopics require creating a new resource file with a lot of repitition, so 100 topics require 100 new files 
     - because of this we had to use helm for one of our other repos
- Configmap Generator does not allow you to extend existing configmaps' data fields (you have to overwrite the whold data field if you fetch a configmap from another kustomize `base`) 
    - the ability to do this would allow us to move more non cluster specific configurations from `aicoe-cd` to this repo
- We can't sops encrypt inline, for example in configmaps 
- Some deployments require fetching existing information like SA tokens to populate the manifest post-deployment, this requires you to deploy, then fetch tokens, then update manifests, then re-deploy again (ideally we should deploy only once) 

All of these issues (save for the last one maybe) can be easily solved by writing some quick Kustomize plugins. 

I was thinking we would include a sub directory in this repo called `kustomize_plugins/operate-first/v1/...` where we write and add these plugins. 

We would then include these plugins as part of the [argocd image](https://quay.io/repository/aicoe/argocd?tag=latest&tab=tags). 
In order to use these plugins locally, you would just `cp` this plugin folder to your `$XDG_HOME_CONFIG/kustomize/plugin/` folder. 

The plugins themselves are very straightforward and easy to write (often only ~50-100 lines), and can be written in bash/go/python or essentially any language (we would likely just use python, something like [this](https://github.com/Agilicus/kustomize-plugins/tree/master/agilicus/v1)). 

What do you guys think?

**Comment by anishasthana** [comment]
I'm a +1 for this. I think the more we can standardize on tools the better (i.e moving away from helm to a python plugin for kustomize)

**Comment by durandom** [comment]
Agreed, less tools is better. 

The plugin should be accompanied with

- a  problem description why the plugin is needed
- an example usage in the `dev` application
