### ISSUE TITLE
Disable GPG key Verification for ArgoCD

### ISSUE THREAD

**Issue by anishasthana** [operate-first/continuous-deployment#80]
ArgoCD attempts to verify the gpg keys that all commits are signed with, resulting in an error stating that a given gpg key is invalid. While one option is to push all contributer public keys to Argocd, it is not needed as github/gitlab  already perform these checks for us. The change to disable it looks like a fairly straightforward  patch too. 

https://argoproj.github.io/argo-cd/user-guide/gpg-verification/

**Comment by anishasthana** [comment]
https://github.com/argoproj/argo-cd/releases/tag/v1.8.1 is out! :-D

**Comment by HumairAK** [comment]
This seems like it's fixed in 1.8.0+ see [here](https://github.com/argoproj/argo-cd/issues/4731)
Let's keep this open and see if the update #82  fixes it.

**Comment by HumairAK** [comment]
Looks like updating to 1.8.1 fixed this.
