### ISSUE TITLE
Determine how to gate changes between environments

### ISSUE THREAD

**Issue by anishasthana** [operate-first/continuous-deployment#83]
We need to figure out a good way to gate/promote changes between environments. Right now we generally default to just updating the base manifest _or_ all the overlays at the same time. 

Assume that we have the following sets of manifests (and environments), all managed by ArgoCD
dev -> stage -> prod-1, prod-2

Our current options are:

**OPTION 1:** Test and verify changes in `dev` -> update the `base` manifests via PR -> deploy and test changes in `stage` -> deploy and test changes in `prod-*`

Pros:

* We will be manually promoting changes and requiring manual verification, so if runbooks are well defined this should be relatively safe

Cons:

* Manual verification can still result in errors
* We aren't using ArgoCD to the fullest
* There will be periods of time where what is in git does not match what is actually deployed

**OPTION 2:** Test and verify changes in `dev` -> update the `base` manifests via PR -> deploy and test changes in `stage` -> Create new tagged release after a number of changes are merged into master -> Update the tagged release that `prod-*` argocd apps are pointed to.

Pros:

* Very easy to tell what is deployed in prod environment (we're basing the deployment on a tagged release)
* Difficult to accidentally push changes to prod.

Cons:

* While lots of small changes may not result in issues, one large change can result in applications crashing
* Slower velocity (not necessarily a bad thing)

**OPTION 3:** Test and verify changes in `dev` -> PR to `stage` overlays -> deploy and verify changes in `stage` -> PR  to `prod-*` overlays -> deploy and verify changes in `prod-*` (This means you basically have 3 copies of the same manifests)

Pros:

* Very deliberate process for promoting changes.

Cons:

* Having three copies of the same manifests goes against the whole idea of overlays and bases. This isn't necessarily bad, but it can be an anti-pattern.
* Harder to determine what is different between environments

**OPTION 4:** Test and verify changes in `dev` -> PR to `stage` overlays -> deploy and verify changes in `stage` -> PR  to revert changes in `stage` manifests and update the `base` manifests -> deploy and verify changes in `prod-*`

Pros:

* Addresses one of the flaws of *3* so that we re-use manifests as much as possible
* Very deliberate process for promoting changes

Cons:

* Revert commits mean that history will be a little messy

**OPTION 5:** Test and verify changes in `dev` -> PR to update `base` manifests -> deploy  in `stage` -> Use ArgoCD [resource hooks](https://argoproj.github.io/argo-cd/user-guide/resource_hooks/) to verify changes -> trigger sync in `prod-*` manifests

Pros:

* Automated, so it will require minimal input from developers once changes are merged in

Cons:

* Will require larger investment to write tests for applications
* This might be a slight mis-use of resource hooks, so we should investigate that

**OPTION 6:** Similar to above, but use something like [keptn](https://github.com/keptn/keptn) for the change gating instead

Pros:

* Automated
* Based on SLIs and SLOs, so it will force us to think more about the health of our services

Cons:

* Will require a lot of investment for getting started

**Comment by tumido** [comment]
**OPTION 1:** We're not here to do stuff manually. :-1: 

**OPTION 2:** This is a very common strategy, with either `release-x.y` branches/tags or even whole `prod` branch. Very well known and used strategy so many should be familiar with the principles already. :+1: 

**OPTION 3:** Very verbose, may be error prone, with multiple copies of the different stage's manifests at the same place. :-1: 

**OPTION 4:** Reverts and moving code in a living codebase to do a release - this will require a lot of review eyes. Release should freeze the code at a certain stable point. This may release completely different codebase to prod, then was used in stage. :-1: 

**OPTION 5:** Very inovative. Would require writing a test suite in ArgoCD resource hooks? I can't imagine it, so I don't know. :man_shrugging: 

**OPTION 6:** A way forward. Automated and based on the things that matters the most. I would love to try this option out. :+1:

**Comment by anishasthana** [comment]
Looks like we're kind of the same page here -- i'm thinking we maybe stick with *OPTION 2* for the time being, and investigate Keptn as well as ArgoCD Resource hooks to see what works better for us. I'm already playing with Keptn, but I don't think I'll be done before I head off for PTO.

Personally I'm leaning towards "we should put in the effort to set up Keptn" as of now.

**Comment by HumairAK** [comment]
Yes I'm a +1 for Option 2, I'm doing something similar with the `operate-first/cd` repository anyways when rolling out changes downstream.

**Comment by HumairAK** [comment]
I think this topic has gone stale, and may be irrelevant, closing -- feel free to reopen if there's more to discuss.
